import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useAccount } from "wagmi";
import { Button } from "@nextui-org/react";

export default function Home() {
  const { data } = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title} style={{ marginBottom: "20px" }}>
          Simple <a href="#">Bank</a>
        </h1>

        <div style={{ paddingTop: "20px" }}> {data?.address}</div>
        <hr />
        <Link href="/home">
          <Button color="gradient" auto>
            Launch App
          </Button>
        </Link>
      </main>
    </div>
  );
}
